# Generated by Django 3.2.2 on 2021-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedproblem',
            name='image',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
    ]
